parameters:
     twig.date_time_format_extension.class: AppBundle\Twig\Extension\DateTimeFormatExtension

services:
    twig.date_time_format_extension:
        class: %twig.date_time_format_extension.class%
        tags:
            - { name: twig.extension }